# Generated by Django 3.2.8 on 2021-11-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previos', models.IntegerField()),
                ('now', models.IntegerField()),
            ],
        ),
    ]
